bascla:
    resource: "@basclaBundle/Resources/config/routing.yml"
    prefix:   /bascla

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

