bascla:
    resource: "@basclaBundle/Resources/config/routing.yml"
    prefix:   /bascla

app:
    resource: '@AppBundle/Controller/'
    type: annotation

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
