bascla_Controller_eventController:
    resource: "@basclaBundle/Resources/config/routing/event.php"
    prefix:   /Controller/eventController

home:
    path:     /home
    defaults:  { _controller: basclaBundle:Default:index }
homeAdmin:
    path:     /homeAdmin
    defaults:  { _controller: basclaBundle:Default:indexAdmin }
products:
    path:     /products
    defaults:  { _controller: basclaBundle:Default:products }
detail:
    path:     /detail
    defaults:  { _controller: basclaBundle:Default:detail }
ajouterEvent:
    path:     /ajouterEvent
    defaults:  { _controller: basclaBundle:Default:ajouterEvent }
modifierEvent:
    path:     /modifierEvent
    defaults:  { _controller: basclaBundle:Default:modifierEvent }
SupprimerEvent:
    path:     /supprimerEvent
    defaults:  { _controller: basclaBundle:Default:supprimerEvent }
CatalogueEvents:
    path:     /CatalogueEvents
    defaults:  { _controller: basclaBundle:Event:CatalogueEvents }
detailEvent:
    path:     /detailEvent/{id}
    defaults:  { _controller: basclaBundle:Event:detailEvent }
ajax_search:
    path:     /search
    defaults:  { _controller: basclaBundle:Event:search }






