bascla_Controller_eventController:
    resource: "@basclaBundle/Resources/config/routing/event.php"
    prefix:   /Controller/eventController

home:
    path:     /home
    defaults:  { _controller: basclaBundle:Default:index }
homeAdmin:
    path:     /homeAdmin
    defaults:  { _controller: basclaBundle:Default:indexAdmin }
products:
    path:     /products
    defaults:  { _controller: basclaBundle:Default:products }

detail:
    path:     /detail
    defaults:  { _controller: basclaBundle:Default:detail }

ajouterEvent:
    path:     /ajouterEvent
    defaults:  { _controller: basclaBundle:Event:ajouterEvent }

afficherEvent:
    path:     /afficherEvent
    defaults:  { _controller: basclaBundle:Event:afficherEvent }
modifierEvent:
    path:     /modifierEvent/{id}
    defaults:  { _controller: basclaBundle:Event:modifierEvent }

supprimerEvent:
    path:     /supprimerEvent/{id}
    defaults:  { _controller: basclaBundle:Event:supprimerEvent }

CatalogueEvents:
    path:     /CatalogueEvents
    defaults:  { _controller: basclaBundle:Event:CatalogueEvents }
detailEvent:
    path:     /detailEvent/{id}
    defaults:  { _controller: basclaBundle:Event:detailEvent }
ajax_search:
    path:     /search
    defaults:  { _controller: basclaBundle:Event:search }






