home:
    path:     /home
    defaults:  { _controller: basclaBundle:Default:index }
homeAdmin:
    path:     /homeAdmin
    defaults:  { _controller: basclaBundle:Default:indexAdmin }
products:
    path:     /products
    defaults:  { _controller: basclaBundle:Default:products }
detail:
    path:     /detail
    defaults:  { _controller: basclaBundle:Default:detail }



